import {useState} from "react";
import {supabase} from "./supabase";

const REASONS={delay:{ar:"تأخير",en:"Delay"},error:{ar:"خطأ",en:"Error"},gift:{ar:"هدية",en:"Gift"}};
const STATUSES={pending_review:{ar:"بانتظار المراجعة",en:"Pending review",c:"#B45309",bg:"#FFFBEB"},approved:{ar:"تمت الموافقة",en:"Approved",c:"#1D4ED8",bg:"#EFF6FF"},paid:{ar:"تم الدفع",en:"Paid",c:"#166534",bg:"#F0FDF4"},rejected:{ar:"مرفوض",en:"Rejected",c:"#B91C1C",bg:"#FEF2F2"},cancelled:{ar:"ملغي",en:"Cancelled",c:"#475569",bg:"#F1F5F9"}};
const money=n=>`${Number(n||0).toFixed(3)} OMR`;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));

export default function RefundsPage({orders,refunds,setRefunds,currentUser,rtl,onNewRequest}){
  const [statusFilter,setStatusFilter]=useState("");
  const [reasonFilter,setReasonFilter]=useState("");
  const [search,setSearch]=useState("");
  const [selected,setSelected]=useState(null);
  const [form,setForm]=useState(null);
  const [comment,setComment]=useState("");
  const [saving,setSaving]=useState(false);
  const isAdmin=currentUser?.role==="admin";
  const tr=(a,e)=>rtl?a:e;
  const orderFor=r=>orders.find(o=>o.id===r.order_id)||{};
  const filtered=refunds.filter(r=>{
    const o=orderFor(r),q=search.trim().toLowerCase();
    return(!statusFilter||r.status===statusFilter)&&(!reasonFilter||r.reason===reasonFilter)&&(!q||String(r.order_id).toLowerCase().includes(q)||String(o.customer||"").toLowerCase().includes(q)||String(o.phone||"").includes(q));
  });
  const paid=refunds.filter(r=>r.status==="paid").reduce((s,r)=>s+Number(r.refund_amount||0),0);
  const pending=refunds.filter(r=>r.status==="pending_review").length;
  const approved=refunds.filter(r=>r.status==="approved").reduce((s,r)=>s+Number(r.refund_amount||0),0);
  const open=r=>{setSelected(r);setForm({affected_jackets:Number(r.affected_jackets||1),approved_unit_value:Number(r.approved_unit_value||r.calculated_unit_value||0),percentage:Number(r.percentage||10),public_note:r.public_note||"",payment_method:r.payment_method||"",payment_ref:r.payment_ref||"",rejection_reason:r.rejection_reason||""});};
  const update=async(patch)=>{
    if(!selected)return;setSaving(true);
    const history=[...(selected.history||[]),{at:new Date().toISOString(),by:currentUser.name,status:patch.status||selected.status}];
    const payload={...patch,history,updated_at:new Date().toISOString()};
    const {data,error}=await supabase.from("compensation_requests").update(payload).eq("id",selected.id).select().single();
    setSaving(false);if(error){alert(error.message);return;}
    setRefunds(p=>p.map(x=>x.id===selected.id?data:x));setSelected(data);open(data);
  };
  const saveReview=()=>{
    const qty=Math.max(1,Math.min(Number(form.affected_jackets),Number(selected.order_jackets)));
    const unit=Math.max(0,Number(form.approved_unit_value));const pct=Math.max(0,Math.min(100,Number(form.percentage)));
    update({affected_jackets:qty,approved_unit_value:unit,percentage:pct,affected_value:qty*unit,refund_amount:qty*unit*pct/100,public_note:form.public_note,payment_method:form.payment_method,payment_ref:form.payment_ref,reviewed_by_name:currentUser.name,reviewed_at:new Date().toISOString()});
  };
  const addComment=async()=>{if(!comment.trim()||!selected)return;const comments=[...(selected.comments||[]),{text:comment.trim(),by:currentUser.name,at:new Date().toISOString()}];setComment("");await update({comments});};
  const printDoc=(r,internal=false)=>{
    const o=orderFor(r),s=STATUSES[r.status]||STATUSES.pending_review,showAmount=["approved","paid"].includes(r.status);
    const calc=internal?`<section><h3>${tr("تفاصيل الحساب","Calculation")}</h3><div class="grid"><p>${tr("قيمة الطلب","Order total")}<b>${money(r.order_total)}</b></p><p>${tr("عدد الجاكيتات","Jackets")}<b>${r.order_jackets}</b></p><p>${tr("الجاكيتات المشمولة","Affected jackets")}<b>${r.affected_jackets}</b></p><p>${tr("قيمة الجاكيت المعتمدة","Approved unit value")}<b>${money(r.approved_unit_value)}</b></p><p>${tr("النسبة","Percentage")}<b>${r.percentage}%</b></p><p>${tr("مبلغ التعويض","Refund amount")}<b>${money(r.refund_amount)}</b></p></div></section>`:(showAmount?`<div class="amount">${tr("مبلغ التعويض المعتمد","Approved compensation")}: ${money(r.refund_amount)}</div>`:"");
    const comments=internal?`<section><h3>${tr("السجل الداخلي","Internal log")}</h3>${[...(r.comments||[])].map(c=>`<p><b>${esc(c.by)}</b> — ${esc(new Date(c.at).toLocaleString())}<br>${esc(c.text)}</p>`).join("")||"--"}</section>`:"";
    const w=window.open("","_blank");if(!w)return;
    w.document.write(`<!doctype html><html dir="${rtl?"rtl":"ltr"}"><head><meta charset="utf-8"><title>Compensation ${r.id}</title><style>@page{size:A4;margin:16mm}body{font-family:Arial,Tahoma;color:#172033;margin:0}.head{display:flex;justify-content:space-between;align-items:center;border-bottom:4px solid #1f2f4f;padding-bottom:14px}.logo{font-size:28px;font-weight:900}.tag{padding:7px 14px;border-radius:20px;background:${s.bg};color:${s.c};font-weight:800}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.grid p,section{border:1px solid #ddd;padding:12px;border-radius:8px}.grid b{display:block;margin-top:5px}.amount{font-size:22px;font-weight:900;border:3px solid #111;padding:16px;margin-top:20px;text-align:center}.foot{margin-top:35px;border-top:1px solid #ddd;padding-top:12px;text-align:center}h3{margin-top:0}</style></head><body><div class="head"><div><div class="logo">THAWB</div><div>${internal?tr("تقرير تعويض داخلي","Internal compensation report"):tr("حالة طلب التعويض","Compensation request status")}</div></div><div class="tag">${rtl?s.ar:s.en}</div></div><section><div class="grid"><p>${tr("رقم طلب التعويض","Request number")}<b>#${r.id}</b></p><p>${tr("رقم الأوردر","Order number")}<b>${esc(r.order_id)}</b></p><p>${tr("العميل","Customer")}<b>${esc(o.customer||"--")}</b></p><p>${tr("رقم الهاتف","Phone")}<b>${esc(o.phone||"--")}</b></p><p>${tr("سبب التعويض","Reason")}<b>${rtl?REASONS[r.reason]?.ar:REASONS[r.reason]?.en}</b></p><p>${tr("تاريخ الطلب","Requested at")}<b>${esc(new Date(r.requested_at).toLocaleString())}</b></p></div><p>${tr("تفاصيل الطلب","Request details")}: ${esc(r.request_comment||"--")}</p>${r.public_note?`<p>${tr("رسالة للعميل","Customer note")}: ${esc(r.public_note)}</p>`:""}</section>${calc}${comments}<div class="foot">THAWB · 72511952</div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close();
  };
  const printReport=()=>{const w=window.open("","_blank");if(!w)return;w.document.write(`<!doctype html><html dir="${rtl?"rtl":"ltr"}"><head><meta charset="utf-8"><title>Compensation Report</title><style>@page{size:A4 landscape;margin:12mm}body{font-family:Arial,Tahoma}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:7px}h1{text-align:center}</style></head><body><h1>${tr("تقرير التعويضات","Compensation Report")}</h1><p>${tr("الإجمالي المدفوع","Total paid")}: ${money(paid)} · ${tr("بانتظار المراجعة","Pending")}: ${pending}</p><table><thead><tr>${[tr("الطلب","Order"),tr("العميل","Customer"),tr("السبب","Reason"),tr("الجاكيتات","Jackets"),tr("النسبة","Rate"),tr("المبلغ","Amount"),tr("الحالة","Status")].map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${filtered.map(r=>{const o=orderFor(r);return `<tr><td>${esc(r.order_id)}</td><td>${esc(o.customer||"--")}</td><td>${rtl?REASONS[r.reason]?.ar:REASONS[r.reason]?.en}</td><td>${r.affected_jackets}/${r.order_jackets}</td><td>${r.percentage}%</td><td>${money(r.refund_amount)}</td><td>${rtl?STATUSES[r.status]?.ar:STATUSES[r.status]?.en}</td></tr>`}).join("")}</tbody></table><script>window.onload=()=>window.print()</script></body></html>`);w.document.close();};
  return <div>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap",marginBottom:20}}><div><h1 style={{margin:0,fontSize:24}}>{tr("التعويضات","Refunds & Compensation")}</h1><div style={{fontSize:13,color:"#64748B"}}>{tr("مراجعة واعتماد ومتابعة تعويضات العملاء","Review, approve and track customer compensation")}</div></div><div style={{display:"flex",gap:8}}><button onClick={printReport} style={btn("#202F4D")}>🖨️ {tr("تقرير","Report")}</button><button onClick={()=>onNewRequest("")} style={btn("#E05E5C")}>+ {tr("طلب تعويض","New request")}</button></div></div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12,marginBottom:18}}>{[[tr("بانتظار المراجعة","Pending review"),pending,"#B45309"],[tr("معتمد ولم يُدفع","Approved unpaid"),money(approved),"#1D4ED8"],[tr("إجمالي المدفوع","Total paid"),money(paid),"#166534"],[tr("إجمالي الحالات","Total cases"),refunds.length,"#202F4D"]].map(([l,v,c])=><div key={l} style={{background:"#fff",border:"1px solid #E2E8F0",borderRadius:12,padding:16}}><div style={{fontSize:12,color:"#64748B"}}>{l}</div><div style={{fontSize:22,fontWeight:900,color:c,marginTop:5}}>{v}</div></div>)}</div>
    <div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:14}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={tr("ابحث بالطلب أو العميل...","Search order or customer...")} style={input}/><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} style={input}><option value="">{tr("كل الحالات","All statuses")}</option>{Object.entries(STATUSES).map(([k,v])=><option key={k} value={k}>{rtl?v.ar:v.en}</option>)}</select><select value={reasonFilter} onChange={e=>setReasonFilter(e.target.value)} style={input}><option value="">{tr("كل الأسباب","All reasons")}</option>{Object.entries(REASONS).map(([k,v])=><option key={k} value={k}>{rtl?v.ar:v.en}</option>)}</select></div>
    <div style={{background:"#fff",border:"1px solid #E2E8F0",borderRadius:12,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{background:"#F1F5F9"}}>{["#",tr("الأوردر","Order"),tr("العميل","Customer"),tr("السبب","Reason"),tr("المبلغ","Amount"),tr("الحالة","Status"),tr("الإجراء","Action")].map(h=><th key={h} style={{padding:12,textAlign:rtl?"right":"left"}}>{h}</th>)}</tr></thead><tbody>{filtered.map(r=>{const o=orderFor(r),s=STATUSES[r.status];return <tr key={r.id} style={{borderTop:"1px solid #E2E8F0"}}><td style={td}>#{r.id}</td><td style={{...td,fontWeight:800}}>{r.order_id}</td><td style={td}>{o.customer||"--"}</td><td style={td}>{rtl?REASONS[r.reason]?.ar:REASONS[r.reason]?.en}</td><td style={{...td,fontWeight:800}}>{money(r.refund_amount)}</td><td style={td}><span style={{background:s.bg,color:s.c,padding:"4px 9px",borderRadius:20,fontWeight:700}}>{rtl?s.ar:s.en}</span></td><td style={td}><button onClick={()=>open(r)} style={smallBtn}>{tr("مراجعة","Review")}</button></td></tr>})}{!filtered.length&&<tr><td colSpan="7" style={{padding:30,textAlign:"center",color:"#64748B"}}>{tr("لا توجد حالات","No cases found")}</td></tr>}</tbody></table></div>
    {selected&&form&&<div style={overlay} onClick={e=>e.target===e.currentTarget&&setSelected(null)}><div style={{background:"#fff",width:760,maxWidth:"95vw",maxHeight:"92vh",overflowY:"auto",borderRadius:16,padding:24,direction:rtl?"rtl":"ltr"}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><h2 style={{margin:0}}>{tr("طلب تعويض","Compensation request")} #{selected.id}</h2><p style={{margin:"4px 0",color:"#64748B"}}>{selected.order_id} · {orderFor(selected).customer}</p></div><button onClick={()=>setSelected(null)} style={closeBtn}>✕</button></div><div style={{background:"#F8FAFC",borderRadius:10,padding:14,margin:"16px 0"}}><b>{tr("سبب الطلب","Reason")}: {rtl?REASONS[selected.reason]?.ar:REASONS[selected.reason]?.en}</b><p>{selected.request_comment||"--"}</p><small>{selected.requested_by_name} · {new Date(selected.requested_at).toLocaleString()}</small></div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><Info l={tr("قيمة الطلب","Order total")} v={money(selected.order_total)}/><Info l={tr("عدد الجاكيتات","Order jackets")} v={selected.order_jackets}/><Info l={tr("القيمة المحسوبة للجاكيت","Calculated unit value")} v={money(selected.calculated_unit_value)}/></div>
      {isAdmin&&<><h3>{tr("مراجعة المدير","Manager review")}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:10}}><Field l={tr("الجاكيتات المشمولة","Affected jackets")} type="number" min="1" max={selected.order_jackets} v={form.affected_jackets} set={v=>setForm(p=>({...p,affected_jackets:v}))}/><Field l={tr("قيمة الجاكيت المعتمدة","Approved unit value")} type="number" step="0.001" v={form.approved_unit_value} set={v=>setForm(p=>({...p,approved_unit_value:v}))}/><Field l={tr("النسبة %","Percentage %")} type="number" min="0" max="100" v={form.percentage} set={v=>setForm(p=>({...p,percentage:v}))}/></div><div style={{background:"#ECFDF5",border:"2px solid #86EFAC",borderRadius:12,padding:16,marginTop:12,display:"flex",justifyContent:"space-between"}}><b>{tr("مبلغ التعويض","Refund amount")}</b><strong style={{fontSize:22,color:"#166534"}}>{money(Number(form.affected_jackets||0)*Number(form.approved_unit_value||0)*Number(form.percentage||0)/100)}</strong></div><label style={label}>{tr("رسالة للعميل","Customer note")}<textarea value={form.public_note} onChange={e=>setForm(p=>({...p,public_note:e.target.value}))} style={{...input,width:"100%",minHeight:70}}/></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Field l={tr("طريقة الدفع","Payment method")} v={form.payment_method} set={v=>setForm(p=>({...p,payment_method:v}))}/><Field l={tr("مرجع الدفع","Payment reference")} v={form.payment_ref} set={v=>setForm(p=>({...p,payment_ref:v}))}/></div><button disabled={saving} onClick={saveReview} style={{...btn("#202F4D"),width:"100%",marginTop:10}}>{tr("حفظ الحساب","Save calculation")}</button><div style={{display:"flex",gap:8,marginTop:10,flexWrap:"wrap"}}>{selected.status==="pending_review"&&<button onClick={()=>update({status:"approved",reviewed_by_name:currentUser.name,reviewed_at:new Date().toISOString()})} style={btn("#1D4ED8")}>✓ {tr("اعتماد","Approve")}</button>}{selected.status==="approved"&&<button onClick={()=>update({status:"paid",paid_by_name:currentUser.name,paid_at:new Date().toISOString(),payment_method:form.payment_method,payment_ref:form.payment_ref})} style={btn("#166534")}>✓ {tr("تأكيد الدفع","Mark paid")}</button>}{!['paid','rejected','cancelled'].includes(selected.status)&&<button onClick={()=>update({status:"rejected",rejection_reason:prompt(tr("سبب الرفض","Rejection reason"))||""})} style={btn("#B91C1C")}>{tr("رفض","Reject")}</button>}</div></>}
      <h3>{tr("التعليقات","Comments")}</h3><div>{(selected.comments||[]).map((c,i)=><div key={i} style={{background:"#F8FAFC",padding:10,borderRadius:8,marginBottom:6}}><b>{c.by}</b><small style={{marginInlineStart:8,color:"#64748B"}}>{new Date(c.at).toLocaleString()}</small><div>{c.text}</div></div>)}</div><div style={{display:"flex",gap:7}}><input value={comment} onChange={e=>setComment(e.target.value)} placeholder={tr("اكتب تعليقًا...","Write a comment...")} style={{...input,flex:1}}/><button onClick={addComment} style={btn("#202F4D")}>{tr("إضافة","Add")}</button></div><div style={{display:"flex",gap:8,marginTop:16,flexWrap:"wrap"}}><button onClick={()=>printDoc(selected,false)} style={btn("#2D7A4F")}>🖨️ {tr("نسخة العميل","Customer copy")}</button>{isAdmin&&<button onClick={()=>printDoc(selected,true)} style={btn("#202F4D")}>🖨️ {tr("التقرير الداخلي","Internal report")}</button>}</div></div></div>}
  </div>;
}
const btn=bg=>({background:bg,color:"#fff",border:0,borderRadius:8,padding:"9px 14px",fontWeight:800,cursor:"pointer"});
const input={border:"1px solid #CBD5E1",borderRadius:8,padding:"9px 11px",fontSize:14,background:"#fff"};
const td={padding:12};const smallBtn={...btn("#202F4D"),padding:"6px 10px",fontSize:12};
const overlay={position:"fixed",inset:0,zIndex:300,background:"rgba(15,23,42,.72)",display:"flex",alignItems:"center",justifyContent:"center"};
const closeBtn={border:"1px solid #CBD5E1",background:"#fff",borderRadius:8,padding:"6px 10px",cursor:"pointer"};
const label={display:"block",fontSize:12,fontWeight:700,marginTop:12};
function Info({l,v}){return <div style={{border:"1px solid #E2E8F0",borderRadius:9,padding:12}}><small style={{color:"#64748B"}}>{l}</small><div style={{fontWeight:900,marginTop:4}}>{v}</div></div>}
function Field({l,v,set,...rest}){return <label style={label}>{l}<input value={v} onChange={e=>set(e.target.value)} style={{...input,width:"100%",marginTop:4}} {...rest}/></label>}
